### ISSUE TITLE
Upgrade Ember.js tracking plan

### ISSUE THREAD

**Issue by raido** [minutebase/ember-inline-svg#113]
This is tracking issue to get project up to date from maintenance side.

- [ ] Upgrade Ember.js to v3.28 -> https://github.com/minutebase/ember-inline-svg/pull/112
- [ ] Upgrade other dependencies
- [ ] Write change log + release v2.x major
